# Generated by Django 6.0.4 on 2026-05-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='temps_de_lecture',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
